### ISSUE TITLE
Add examples of caching and deployments 

### ISSUE THREAD

**Issue by Mateiadrielrafael** [typhon-ci/typhon#25]
Hi! 

I've come here after watching the fosdem talk. The project looks pretty neat, but it would be nice if the docs included examples of:
- uploading the built artifacts to a binary cache
- deploying things pushed on certain branches

**Comment by pnmadelaine** [comment]
At the moment it is a bit of a pain to do, but I am in the process of reworking the library to make writing deployments easier. As soon as it is done I will write an example of deployment on cachix!
