### ISSUE TITLE
Evaluation is not triggered on new jobsets

### ISSUE THREAD

**Issue by pnmadelaine** [typhon-ci/typhon#3]
While using `mkGithubProject`, branch creations correctly spawn new jobsets but they are not evaluated.
This can be worked around by evaluating manually or pushing a new commit to the same branch.

**Comment by evanrichter** [comment]
or if using `mkGiteaProject`, you can click "replay this webhook" on the failed webhook:

![image](https://github.com/typhon-ci/typhon/assets/330292/09392c6b-15f8-4743-a97d-9edac7591573)
