### ISSUE TITLE
gitea: jobsets not updating

### ISSUE THREAD

**Issue by evanrichter** [typhon-ci/typhon#42]
I set up a combined/self-referencing config/project repo while reading the guide: https://doc.typhon-ci.org/usage.html but for my local gitea.

In the typhon webui, I set the project url to "git+https://gitea/owner/repo" instead of the "github:" style flake url. I left the "flake" checkbox checked.

Refresh turns into a green check.

Clicking "update Jobsets" does not do anything, nor even make a request to my gitea.

**Comment by pnmadelaine** [comment]
Thank you for trying Typhon! Sorry for the inconvenience of setting up a project, we will try to make the process more smooth in the future.

> In the typhon webui, I set the project url to "git+https://gitea/owner/repo" instead of the "github:" style flake url. I left the "flake" checkbox checked.

That's good, do you also get a locked flake URL?

Make sure that the `instance` attribute is passed to `lib.gitea.mkProject` and properly links to the domain of your gitea instance. Also verify that you added a `gitea_token` to your secrets and that it has read access to the repository.

If all this is done and you still don't get an update, please try running the action locally and see if you get an output:

```bash
nix build .#typhonProject.actions.x86_64-linux
echo '{"gitea_token": "…"}' | result/jobsets
```

Don't forget to refresh the project every time you update the configuration!

**Comment by evanrichter** [comment]
thanks for the helpful debugging steps!

the jobsets script contained `https://https://gitea/api/v1/repos/owner/repo/branches` (with a double https scheme!). I removed the "https://" from my `instance` and now it works! No wonder my gitea (nor wireshark) was seeing any traffic for jobset updates.

**Comment by pnmadelaine** [comment]
no problem, I'm happy it was simple to debug :D
