### ISSUE TITLE
Handles are not urlencoded

### ISSUE THREAD

**Issue by W95Psp** [typhon-ci/typhon#9]
We don't escape project names, jobset names and jobset system in URLs.
That's important especially for branches:  a branch with a `/` results in 404 errors in botht the API and webapp.

**Comment by pnmadelaine** [comment]
Job names suffer the same problem! Project names, jobset names, job systems and job names are all arbitrary strings.

**Comment by pnmadelaine** [comment]
I can't reproduce the issue on the API though, it seems like Actix does the URL decoding automatically and this is only a problem in the webapp. For instance, this currently works as expected:
```
curl https://etna.typhon-ci.org/api/projects/typhon/jobsets/lucas%2Fsettings-oncecell
```

**Comment by pnmadelaine** [comment]
Actually, the leptos router seems to also do the decoding automatically (https://etna.typhon-ci.org/project/typhon/jobset/lucas%2Fsettings-oncecell?page=1 works).

So I guess there is nothing to do in terms of decoding and we just have to update https://github.com/typhon-ci/typhon/blob/b7fd60b72e51992b6f38857f0fa78d67edfb332f/typhon-webapp/src/routes.rs#L282 to do the encoding.
